### ISSUE TITLE
画像のアップロード機能

### ISSUE THREAD

**Issue by RossyWhite** [takeyuwebinc/takeyuweb-rails#31]
rails5.2にアップデートできたら、追加する

#25

**Comment by takeyuweb** [comment]
Herokuではローカルストレージは使えないので、クラウドストレージを使うようにする必要があります。

S3を使うようにしましょう。

**Comment by takeyuweb** [comment]
S3で動くことが確認できたら、開発用にはS3クローンなんかをDockerで立てるようにしてそっち使いたくもある

https://hub.docker.com/r/minio/minio/

**Comment by RossyWhite** [comment]
なるほど、了解しました。

**Comment by RossyWhite** [comment]
rails5.2で、`encrypted secrets` はdeprecatedになって`encrypted credentials`に置きかわるらしいのですが、`encrypted credentials`で大丈夫ですか?
@takeyuweb

**Comment by takeyuweb** [comment]
あぁーそうでしたね `encrypted secrets` 儚い

Credentials 試しますか
https://www.engineyard.com/blog/rails-encrypted-credentials-on-rails-5.2
