### ISSUE TITLE
Heroku Review Apps

### ISSUE THREAD

**Issue by takeyuweb** [takeyuwebinc/takeyuweb-rails#46]
せっかくHerokuを使っているので、 Heroku Review Apps を使えたらなーと思いました。
こちら設定試してもらえますか？
必要な操作や権限等があればお伝えください。

**Comment by RossyWhite** [comment]
了解しました。

**Comment by RossyWhite** [comment]
@takeyuweb 

heroku pipelineというのを作ってアプリを登録しないといけないのですが、
ownerでないとできないみたいです:cry:
